/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   20
#define gattdb_board_rev                      22
#define gattdb_firmware_rev                   24
#define gattdb_system_id                      26
#define gattdb_current_time                   29
#define gattdb_local_time_information         32
#define gattdb_reference_time_information     34
#define gattdb_HoursToSleep                   37
#define gattdb_ota_control                    41
#define gattdb_iaq_eco2                       44
#define gattdb_iaq_tvoc                       46
#define gattdb_es_sound_level                 49
#define gattdb_es_pressure                    51
#define gattdb_es_temperature                 53
#define gattdb_es_humidity                    55
#define gattdb_es_uvindex                     57
#define gattdb_es_ambient_light               59
#define gattdb_hall_state                     62
#define gattdb_hall_field_strength            65
#define gattdb_hall_control_point             68
#define gattdb_aio_digital_in                 71
#define gattdb_aio_num_of_digitals_in         74
#define gattdb_aio_digital_out                76
#define gattdb_aio_num_of_digitals_out        78
#define gattdb_ui_rgbleds                     81
#define gattdb_batt_measurement               84
#define gattdb_power_source_type              88
#define gattdb_imu_acceleration               91
#define gattdb_imu_orientation                94
#define gattdb_imu_control_point              97


#endif // __GATT_DB_H
